In [ ]:
!pip install openai anthropic
!pip install pytest tabulate

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (1.109.1)
Collecting anthropic
  Downloading anthropic-0.71.0-py3-none-any.whl.metadata (28 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.11.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.11.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.17.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Downloading anthropic-0.71.0-py3-none-any.whl (355 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 355.0/355.0 kB 8.2 MB/s eta 0:00:00
Installing collected packages: anthropic
Successfully installed anthropic-0.71.0
Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (8.4.2)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (0.9.0)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.1.0)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from pytest) (25.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.19.2)

In [ ]:
!pip install openai google-generativeai tabulate pytest

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (1.109.1)
Requirement already satisfied: google-generativeai in /usr/local/lib/python3.12/dist-packages (0.8.5)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (0.9.0)
Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (8.4.2)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.11.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.11.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.26.0)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.184.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.38.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.26.1)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.1.0)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from pytest) (25.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.19.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai) (1.70.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai) (2.32.4)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.31.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.75.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.5)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.5.0)

In [ ]:
!git clone https://github.com/openai/human-eval.git
%cd human-eval

Cloning into 'human-eval'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 34 (delta 11), reused 4 (delta 4), pack-reused 9 (from 2)
Receiving objects: 100% (34/34), 55.87 KiB | 866.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
/content/human-eval

In [ ]:
!pip install evalplus

Collecting evalplus
  Downloading evalplus-0.3.1-py3-none-any.whl.metadata (12 kB)
Collecting wget>=3.2 (from evalplus)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Collecting tempdir>=0.7.1 (from evalplus)
  Downloading tempdir-0.7.1.tar.gz (5.9 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: multipledispatch>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from evalplus) (1.0.0)
Collecting appdirs>=1.4.4 (from evalplus)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from evalplus) (2.0.2)
Requirement already satisfied: tqdm>=4.56.0 in /usr/local/lib/python3.12/dist-packages (from evalplus) (4.67.1)
Requirement already satisfied: termcolor>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evalplus) (3.1.0)
Collecting fire>=0.6.0 (from evalplus)
  Downloading fire-0.7.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: openai>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from evalplus) (1.109.1)
Collecting tree-sitter>=0.22.0 (from evalplus)
  Downloading tree_sitter-0.25.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Collecting tree-sitter-python>=0.21.0 (from evalplus)
  Downloading tree_sitter_python-0.25.0-cp310-abi3-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (1.9 kB)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from evalplus) (13.9.4)
Requirement already satisfied: transformers>=4.43.0 in /usr/local/lib/python3.12/dist-packages (from evalplus) (4.57.1)
Collecting stop-sequencer>=1.2.3 (from evalplus)
  Downloading stop-sequencer-1.2.3.tar.gz (3.7 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: anthropic>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from evalplus) (0.71.0)
Requirement already satisfied: google-generativeai>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from evalplus) (0.8.5)
Requirement already satisfied: datasets>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from evalplus) (4.0.0)
Requirement already satisfied: psutil>=5.9.0 in /usr/local/lib/python3.12/dist-packages (from evalplus) (5.9.5)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.34.1->evalplus) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.34.1->evalplus) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.34.1->evalplus) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.34.1->evalplus) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.34.1->evalplus) (0.11.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.34.1->evalplus) (2.11.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.34.1->evalplus) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.34.1->evalplus) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->evalplus) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (0.35.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->evalplus) (6.0.3)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.12/dist-packages (from google-generativeai>=0.7.2->evalplus) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.12/dist-packages (from google-generativeai>=0.7.2->evalplus) (2.26.0)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (from google-generativeai>=0.7.2->evalplus) (2.184.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from google-generativeai>=0.7.2->evalplus) (2.38.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from google-generativeai>=0.7.2->evalplus) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai>=0.7.2->evalplus) (1.26.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->evalplus) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->evalplus) (2.19.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0->evalplus) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0->evalplus) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0->evalplus) (0.6.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->anthropic>=0.34.1->evalplus) (3.11)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->evalplus) (3.13.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai>=0.7.2->evalplus) (1.70.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai>=0.7.2->evalplus) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai>=0.7.2->evalplus) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai>=0.7.2->evalplus) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic>=0.34.1->evalplus) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic>=0.34.1->evalplus) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic>=0.34.1->evalplus) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets>=2.21.0->evalplus) (1.1.10)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->evalplus) (0.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic>=0.34.1->evalplus) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic>=0.34.1->evalplus) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic>=0.34.1->evalplus) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.21.0->evalplus) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.21.0->evalplus) (2.5.0)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai>=0.7.2->evalplus) (0.31.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai>=0.7.2->evalplus) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai>=0.7.2->evalplus) (4.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.21.0->evalplus) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.21.0->evalplus) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.21.0->evalplus) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->evalplus) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->evalplus) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->evalplus) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->evalplus) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->evalplus) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->evalplus) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->evalplus) (1.22.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai>=0.7.2->evalplus) (1.75.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai>=0.7.2->evalplus) (1.71.2)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai>=0.7.2->evalplus) (3.2.5)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai>=0.7.2->evalplus) (0.6.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.21.0->evalplus) (1.17.0)
Downloading evalplus-0.3.1-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 4.1 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading fire-0.7.1-py3-none-any.whl (115 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 kB 7.2 MB/s eta 0:00:00
Downloading tree_sitter-0.25.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (635 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 635.4/635.4 kB 29.0 MB/s eta 0:00:00
Downloading tree_sitter_python-0.25.0-cp310-abi3-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.1/108.1 kB 9.2 MB/s eta 0:00:00
Building wheels for collected packages: stop-sequencer, tempdir, wget
  Building wheel for stop-sequencer (setup.py) ... done
  Created wheel for stop-sequencer: filename=stop_sequencer-1.2.3-py3-none-any.whl size=4869 sha256=e02716d0c834dc2178c0bf880df7b8c4435d91110c97cd9dcfb5fa94324bb0ce
  Stored in directory: /root/.cache/pip/wheels/b4/a3/12/0c6a6541ed0eafd69c075930baea3a103ae49c7d03de988290
  Building wheel for tempdir (setup.py) ... done
  Created wheel for tempdir: filename=tempdir-0.7.1-py3-none-any.whl size=2194 sha256=e011b40a1989b661e3a37a03aeb298ab010c75782e8e4259b91eecf857915745
  Stored in directory: /root/.cache/pip/wheels/1e/14/6b/dedd96c73357be1d37d03b56a8bcfc5425df347e05115ac18c
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=a3be2fcb80e57cca8917ac75775c6f76784e9f85276703a0951a23557a978dca
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built stop-sequencer tempdir wget
Installing collected packages: wget, tempdir, appdirs, tree-sitter-python, tree-sitter, fire, stop-sequencer, evalplus
Successfully installed appdirs-1.4.4 evalplus-0.3.1 fire-0.7.1 stop-sequencer-1.2.3 tempdir-0.7.1 tree-sitter-0.25.2 tree-sitter-python-0.25.0 wget-3.2

In [ ]:
from evalplus.data import get_human_eval_plus

problems = get_human_eval_plus()   # instead of get_human_eval()
print(f"Loaded {len(problems)} problems")

Downloading dataset from https://github.com/evalplus/humanevalplus_release/releases/download/v0.1.10/HumanEvalPlus.jsonl.gz
Loaded 164 problems

In [ ]:
first_key = list(problems.keys())[0]
print(first_key)
print(problems[first_key]["prompt"])

HumanEval/0
from typing import List


def has_close_elements(numbers: List[float], threshold: float) -> bool:
    """ Check if in given list of numbers, are any two numbers closer to each other than
    given threshold.
    >>> has_close_elements([1.0, 2.0, 3.0], 0.5)
    False
    >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)
    True
    """

In [ ]:
# selected = list(problems.keys())[:10]
# print("Selected problems:", selected)

Selected problems: ['HumanEval/0', 'HumanEval/1', 'HumanEval/2', 'HumanEval/3', 'HumanEval/4', 'HumanEval/5', 'HumanEval/6', 'HumanEval/7', 'HumanEval/8', 'HumanEval/9']

In [ ]:
import os
os.environ["OPENAI_API_KEY"] = ""
os.environ["GOOGLE_API_KEY"] = ""

In [ ]:
from openai import OpenAI
gpt = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

In [ ]:
import google.generativeai as genai
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])
# List available models to find a supported one
# for m in genai.list_models():
#   if 'generateContent' in m.supported_generation_methods:
#     print(m.name)
GEMINI_MODEL = "models/gemini-2.5-flash" # Update with a supported model if the above list reveals a different one.

In [ ]:
def chain_of_thought(problem_text):
    return f"""
You are a skilled Python developer.
{problem_text}
Think step by step about the logic before writing the code.
Then write the final, correct function implementation.
"""

def stepwise_chain_of_thought(problem_text):
    return f"""
You are to solve the following problem step-by-step.

1. Break down the logic clearly in small numbered steps.
2. Then write the Python function.
3. Double-check for correctness and edge cases.

Problem:
{problem_text}
"""

In [ ]:
def generate_code_gpt(prompt):
    response = gpt.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
    )
    return response.choices[0].message.content.strip()

def generate_code_gemini(prompt):
    model = genai.GenerativeModel(GEMINI_MODEL)
    response = model.generate_content(prompt)
    return response.text.strip()

In [ ]:
import io, contextlib

def check_pass(problem, code):
    full_code = code + "\n" + problem["test"]
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            exec(full_code, {})
        return 1
    except Exception as e:
        return 0

Part1

In [ ]:
import pandas as pd

# select 10 problems as dictionary
selected = {k: problems[k] for k in list(problems.keys())[:10]}
print("Selected problems:", list(selected.keys()))

strategies = [("CoT", chain_of_thought), ("SCoT", stepwise_chain_of_thought)]
records = []

for pid, prob in selected.items():
    for strat_name, strat_fn in strategies:
        prompt = strat_fn(prob["prompt"])

        # GPT
        gpt_code = generate_code_gpt(prompt)
        gpt_pass = check_pass(prob, gpt_code)
        records.append([pid, "GPT-4o-mini", strat_name, gpt_pass])

        # Gemini
        gem_code = generate_code_gemini(prompt)
        gem_pass = check_pass(prob, gem_code)
        records.append([pid, GEMINI_MODEL, strat_name, gem_pass])

df = pd.DataFrame(records, columns=["Problem", "Model", "PromptType", "Pass@1"])
df.to_csv("results_part1.csv", index=False)
df

Selected problems: ['HumanEval/0', 'HumanEval/1', 'HumanEval/2', 'HumanEval/3', 'HumanEval/4', 'HumanEval/5', 'HumanEval/6', 'HumanEval/7', 'HumanEval/8', 'HumanEval/9']

        Problem             Model PromptType  Pass@1
0   HumanEval/0       GPT-4o-mini        CoT       0
1   HumanEval/0  gemini-2.5-flash        CoT       0
2   HumanEval/0       GPT-4o-mini       SCoT       0
3   HumanEval/0  gemini-2.5-flash       SCoT       0
4   HumanEval/1       GPT-4o-mini        CoT       0
5   HumanEval/1  gemini-2.5-flash        CoT       0
6   HumanEval/1       GPT-4o-mini       SCoT       0
7   HumanEval/1  gemini-2.5-flash       SCoT       0
8   HumanEval/2       GPT-4o-mini        CoT       0
9   HumanEval/2  gemini-2.5-flash        CoT       0
10  HumanEval/2       GPT-4o-mini       SCoT       0
11  HumanEval/2  gemini-2.5-flash       SCoT       0
12  HumanEval/3       GPT-4o-mini        CoT       0
13  HumanEval/3  gemini-2.5-flash        CoT       0
14  HumanEval/3       GPT-4o-mini       SCoT       0
15  HumanEval/3  gemini-2.5-flash       SCoT       0
16  HumanEval/4       GPT-4o-mini        CoT       0
17  HumanEval/4  gemini-2.5-flash        CoT       0
18  HumanEval/4       GPT-4o-mini       SCoT       0
19  HumanEval/4  gemini-2.5-flash       SCoT       0
20  HumanEval/5       GPT-4o-mini        CoT       0
21  HumanEval/5  gemini-2.5-flash        CoT       0
22  HumanEval/5       GPT-4o-mini       SCoT       0
23  HumanEval/5  gemini-2.5-flash       SCoT       0
24  HumanEval/6       GPT-4o-mini        CoT       0
25  HumanEval/6  gemini-2.5-flash        CoT       0
26  HumanEval/6       GPT-4o-mini       SCoT       0
27  HumanEval/6  gemini-2.5-flash       SCoT       0
28  HumanEval/7       GPT-4o-mini        CoT       0
29  HumanEval/7  gemini-2.5-flash        CoT       0
30  HumanEval/7       GPT-4o-mini       SCoT       0
31  HumanEval/7  gemini-2.5-flash       SCoT       0
32  HumanEval/8       GPT-4o-mini        CoT       0
33  HumanEval/8  gemini-2.5-flash        CoT       0
34  HumanEval/8       GPT-4o-mini       SCoT       0
35  HumanEval/8  gemini-2.5-flash       SCoT       0
36  HumanEval/9       GPT-4o-mini        CoT       0
37  HumanEval/9  gemini-2.5-flash        CoT       0
38  HumanEval/9       GPT-4o-mini       SCoT       0
39  HumanEval/9  gemini-2.5-flash       SCoT       0

Pass@1 = 0 → the generated code failed at least one test case in the HumanEval problem.

Pass@1 = 1 → the generated code passed all test cases.

In [ ]:
import pandas as pd
import re
import os
from google.colab import files


# --- Step 1: Utility functions ---

def extract_code(text):
    """
    Remove markdown or explanation text to leave clean Python code.
    """
    if not text:
        return ""
    code = re.sub(r"```(?:python)?\n", "", text)
    code = re.sub(r"```", "", code)
    return code.strip()

def generate_code_gpt(prompt):
    """
    Replace with your GPT API call
    """
    # Example for OpenAI
    import openai
    response = openai.ChatCompletion.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )
    text = response.choices[0].message.content
    return extract_code(text)

def generate_code_gemini(prompt):
    """
    Uses Google Gemini
    """
    model = genai.GenerativeModel(GEMINI_MODEL)
    response = model.generate_content(prompt)
    if hasattr(response, "text") and response.text:
        return extract_code(response.text)
    elif hasattr(response, "candidates") and response.candidates:
        return extract_code(response.candidates[0].content.parts[0].text)
    else:
        return ""

def check_pass(problem, code):
    """
    Execute the problem's test cases safely
    Returns 1 if all pass, 0 if any fail
    """
    try:
        # 'problem["test"]' should contain the test code
        local_vars = {}
        exec(code, {}, local_vars)
        exec(problem["test"], {}, local_vars)
        return 1
    except Exception as e:
        return 0

# --- Step 2: Refined prompting functions ---

def chain_of_thought_refined(problem_text):
    return f"""
You are a Python expert.
Write a function that strictly follows the given signature.
Include all edge cases (empty lists, negative numbers, zero, invalid inputs if applicable).
Do not add any explanation — only provide the function code.

Problem:
{problem_text}
"""

def stepwise_chain_of_thought_refined(problem_text):
    return f"""
You are a Python expert.
Solve the problem step by step.
1. Plan your approach.
2. Implement the function following the signature.
3. Include edge cases.
Do not add explanations outside the code.

Problem:
{problem_text}
"""

# --- Step 3: Select 10 problems ---
selected = {k: problems[k] for k in list(problems.keys())[:10]}
print("Selected problems:", list(selected.keys()))

# --- Step 4: Run evaluation ---
strategies = [("CoT", chain_of_thought_refined), ("SCoT", stepwise_chain_of_thought_refined)]
records = []

for pid, prob in selected.items():
    for strat_name, strat_fn in strategies:
        prompt = strat_fn(prob["prompt"])

        # GPT
        gpt_code = generate_code_gpt(prompt)
        gpt_pass = check_pass(prob, gpt_code)
        records.append([pid, "GPT-4o-mini", strat_name, gpt_pass, prompt, gpt_code])

        # Gemini
        gem_code = generate_code_gemini(prompt)
        gem_pass = check_pass(prob, gem_code)
        records.append([pid, GEMINI_MODEL, strat_name, gem_pass, prompt, gem_code])

# --- Step 5: Save results ---
df = pd.DataFrame(records, columns=["Problem", "Model", "PromptType", "Pass@1", "Prompt", "GeneratedCode"])
csv_path = "/content/results_part1_refined.csv"
df.to_csv(csv_path, index=False)
files.download(csv_path)
df

Selected problems: ['HumanEval/0', 'HumanEval/1', 'HumanEval/2', 'HumanEval/3', 'HumanEval/4', 'HumanEval/5', 'HumanEval/6', 'HumanEval/7', 'HumanEval/8', 'HumanEval/9']
False
False
True
False
False
['()', '(())', '(()())']
['()']
['((()))']
['()', '()', '()']
['()', '(())', '(())']
[]
False
True
False
True
True
0.0
0.0
0.0
0.6666666666666666
[]
[1, 4, 2, 4, 3]
[5]
[1, -1, 2]
[1, 0, 2, 0, 3, 0, 4]
[2, 3, 1, 3]
[1, 1, 1]
[]
[5]
[1]
(0, 1)
(10, 24)
(-6, -6)
(3, 0)
(5, 5)
[]
[5]
[-1, -1, -1, -1]
[1, 1, 1, 1]
[1, 3, 3, 5, 5]

,Problem,Model,PromptType,Pass@1,Prompt,GeneratedCode
0,HumanEval/0,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\ndef has_close_eleme...
1,HumanEval/0,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\n\ndef has_close_ele...
2,HumanEval/0,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\ndef has_close_eleme...
3,HumanEval/0,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\n\ndef has_close_ele...
4,HumanEval/1,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\ndef separate_paren_...
5,HumanEval/1,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\n\ndef separate_pare...
6,HumanEval/1,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\ndef separate_paren_...
7,HumanEval/1,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\n\ndef separate_pare...
8,HumanEval/2,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,def truncate_number(number: float) -> float:\n...
9,HumanEval/2,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,import math\n\ndef truncate_number(number: flo...
10,HumanEval/2,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,def truncate_number(number: float) -> float:\n...
11,HumanEval/2,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,import math\n\ndef truncate_number(number: flo...
12,HumanEval/3,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\ndef below_zero(oper...
13,HumanEval/3,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\n\ndef below_zero(op...
14,HumanEval/3,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\ndef below_zero(oper...
15,HumanEval/3,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\n\ndef below_zero(op...
16,HumanEval/4,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\ndef mean_absolute_d...
17,HumanEval/4,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\n\ndef mean_absolute...
18,HumanEval/4,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\ndef mean_absolute_d...
19,HumanEval/4,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\n\ndef mean_absolute...
20,HumanEval/5,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\ndef intersperse(num...
21,HumanEval/5,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\n\ndef intersperse(n...
22,HumanEval/5,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\ndef intersperse(num...
23,HumanEval/5,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\n\ndef intersperse(n...
24,HumanEval/6,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\ndef parse_nested_pa...
25,HumanEval/6,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\n\ndef parse_nested_...
26,HumanEval/6,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\ndef parse_nested_pa...
27,HumanEval/6,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\n\ndef parse_nested_...
28,HumanEval/7,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\ndef filter_by_subst...
29,HumanEval/7,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\n\ndef filter_by_sub...
30,HumanEval/7,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\ndef filter_by_subst...
31,HumanEval/7,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\n\ndef filter_by_sub...
32,HumanEval/8,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,"from typing import List, Tuple\n\ndef sum_prod..."
33,HumanEval/8,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,"from typing import List, Tuple\n\n\ndef sum_pr..."
34,HumanEval/8,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,"from typing import List, Tuple\n\ndef sum_prod..."
35,HumanEval/8,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,"from typing import List, Tuple\n\n\ndef sum_pr..."
36,HumanEval/9,GPT-4o-mini,CoT,1,\nYou are a Python expert.\nWrite a function t...,from typing import List\n\ndef rolling_max(num...
37,HumanEval/9,gemini-2.5-flash,CoT,1,\nYou are a Python expert.\nWrite a function t...,"from typing import List, Tuple\n\n\ndef rollin..."
38,HumanEval/9,GPT-4o-mini,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,from typing import List\n\ndef rolling_max(num...
39,HumanEval/9,gemini-2.5-flash,SCoT,1,\nYou are a Python expert.\nSolve the problem ...,"from typing import List, Tuple\n\n\ndef rollin..."

In [ ]:
!pip install datasets huggingface_hub gdown

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.35.3)
Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.20.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.1.10)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2025.10.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
!huggingface-cli login

⚠️  Warning: 'huggingface-cli login' is deprecated. Use 'hf auth login' instead.

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To log in, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible):
Add token as git credential? (Y/n) y
Token is valid (permission: fineGrained).
The token `520ex1` has been saved to /root/.cache/huggingface/stored_tokens
Cannot authenticate through git-credential as no helper is defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub.
Run the following command in your terminal in case you want to set the 'store' credential helper as default.

git config --global credential.helper store

Read https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage for more details.
Token has not been saved to git credential helper.
Your token has been saved to /root/.cache/huggingface/token
Login successful.
The current active token is: `520ex1`

In [ ]:
# ------------------------
# Load APPS Dataset (Official)
# ------------------------
from datasets import load_dataset

# Choose "default" or "verified"
apps_dataset = load_dataset("Elfsong/APPS", "default", split="test")

# Filter only harder problems (competition-level)
apps_hard = [p for p in apps_dataset if p.get("difficulty", "") == "competition"]
selected_apps = apps_hard[:3]  # select 5 challenging problems

print(f"Loaded {len(selected_apps)} hard APPS problems for Part 2.\n")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/41.0M [00:00<?, ?B/s]

data/test-00000-of-00003.parquet:   0%|          | 0.00/256M [00:00<?, ?B/s]

data/test-00001-of-00003.parquet:   0%|          | 0.00/184M [00:00<?, ?B/s]

data/test-00002-of-00003.parquet:   0%|          | 0.00/303M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4805 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3765 [00:00<?, ? examples/s]

Loaded 3 hard APPS problems for Part 2.

In [ ]:
selected_apps[1]

{'problem_id': 3690,
 'question': 'Have you ever tried to explain to the coordinator, why it is eight hours to the contest and not a single problem has been prepared yet? Misha had. And this time he has a really strong excuse: he faced a space-time paradox! Space and time replaced each other.\n\nThe entire universe turned into an enormous clock face with three hands\xa0— hour, minute, and second. Time froze, and clocks now show the time h hours, m minutes, s seconds.\n\nLast time Misha talked with the coordinator at t_1 o\'clock, so now he stands on the number t_1 on the clock face. The contest should be ready by t_2 o\'clock. In the terms of paradox it means that Misha has to go to number t_2 somehow. Note that he doesn\'t have to move forward only: in these circumstances time has no direction.\n\nClock hands are very long, and Misha cannot get round them. He also cannot step over as it leads to the collapse of space-time. That is, if hour clock points 12 and Misha stands at 11 then he cannot move to 1 along the top arc. He has to follow all the way round the clock center (of course, if there are no other hands on his way).\n\nGiven the hands\' positions, t_1, and t_2, find if Misha can prepare the contest on time (or should we say on space?). That is, find if he can move from t_1 to t_2 by the clock face.\n\n\n-----Input-----\n\nFive integers h, m, s, t_1, t_2 (1 ≤ h ≤ 12, 0 ≤ m, s ≤ 59, 1 ≤ t_1, t_2 ≤ 12, t_1 ≠ t_2).\n\nMisha\'s position and the target time do not coincide with the position of any hand.\n\n\n-----Output-----\n\nPrint "YES" (quotes for clarity), if Misha can prepare the contest on time, and "NO" otherwise.\n\nYou can print each character either upper- or lowercase ("YeS" and "yes" are valid when the answer is "YES").\n\n\n-----Examples-----\nInput\n12 30 45 3 11\n\nOutput\nNO\n\nInput\n12 0 1 12 1\n\nOutput\nYES\n\nInput\n3 47 0 4 9\n\nOutput\nYES\n\n\n\n-----Note-----\n\nThe three examples are shown on the pictures below from left to right. The starting position of Misha is shown with green, the ending position is shown with pink. Note that the positions of the hands on the pictures are not exact, but are close to the exact and the answer is the same. $\\oplus 0 \\theta$',
 'solutions': '["used = [0] * 121\\nh, m, s, t1, t2 = map(int, input().split())\\nh %= 12\\nt1 %= 12\\nt2 %= 12\\nt1 *= 5\\nt2 *= 5\\nused[h * 5] = 1\\nused[h * 5 + 60] = 1\\nused[m] = 1\\nused[m + 60] = 1\\nused[s] = 1\\nused[s + 60] = 1\\nif t1 > t2:\\n    t1, t2 = t2, t1\\nt3 = t1 + 60\\nif sum(used[t1:t2]) == 0 or sum(used[t2:t3]) == 0:\\n    print(\\"YES\\")\\nelse:\\n    print(\\"NO\\")", "h,m,s,t1,t2 = list(map(int,input().split()))\\nh %= 12\\narr = []\\narr.append(h*30 + m/2 + s/120)\\narr.append(6*m + s/10)\\narr.append(6*s)\\narr.sort()\\narr = arr + [(360 + arr[0])]\\n\\nt1 *= 30\\nt2 *= 30\\n\\nx1 = -1\\nx2 = -1\\nfor i in range(3):\\n\\tif((arr[i] <= t1 and t1 <= arr[i+1]) or (arr[i] <= t1+360 and t1+360 <= arr[i+1])):\\n\\t\\tx1 = i\\n\\tif((arr[i] <= t2 and t2 <= arr[i+1]) or (arr[i] <= t2+360 and t2+360 <= arr[i+1])):\\n\\t\\tx2 = i\\n\\nprint(\'YES\' if x1==x2 else \'NO\')\\n", "from sys import stdin, stdout\\n\\nh, m, s, t1, t2 = list(map(int,stdin.readline().rstrip().split()))\\n\\nh+=0.1\\nm+=0.1\\n\\nif t1>t2:\\n    t1,t2 = t2,t1\\n\\nbetweenCount = 0\\nif h<t2 and h>t1:\\n    betweenCount+=1\\nif m<t2*5 and m>t1*5:\\n    betweenCount+=1\\nif s<t2*5 and s>t1*5:\\n    betweenCount+=1\\n\\nif betweenCount==3 or betweenCount==0:\\n    print(\\"YES\\")\\nelse:\\n    print(\\"NO\\")\\n", "h, m, s, t1, t2 = [int(i) for i in input().split()]\\nh *= 5\\nt1 *= 5\\nt2 *= 5\\nif h < t1: h += 60\\nif m < t1: m += 60\\nif s < t1: s += 60\\nif t2 < t1: t2 += 60\\nc = (t2 <= h) + (t2 <= m) + (t2 <= s)\\nans = \\"YES\\" if c == 0 or c == 3 else \\"NO\\"\\nprint(ans)\\n", "h, m, s, t1, t2 = map(int, input().split())\\nm //= 5\\ns //= 5\\na = [h, m, s, h + 12, m + 12, s + 12]\\nup = 1\\ndw = 1\\nif t1 > t2:\\n\\tt1, t2 = t2, t1\\nt1u = t1 + 12\\nfor i in a:\\n\\tif t1 <= i and i < t2:\\n\\t\\tup = 0\\n\\tif t2 <= i and i < t1u:\\n\\t\\tdw = 0\\nif dw + up == 0:\\n\\tprint(\'NO\')\\nelse:\\n\\tprint(\'YES\') ", "h, m, s, t1, t2 = list(map(int, input().split()))\\nh = h % 12\\nt1 = t1 % 12\\nt2 = t2 % 12\\n\\nt1 = t1 * 60 * 60\\nt2 = t2 * 60 * 60\\nt1, t2 = min(t1, t2), max(t1, t2)\\n\\nhourHand = h * 60 * 60 + m * 60 + s\\nminHand = (m * 60 + s) * 12\\nsecondHand = (s) * 60 * 12\\n\\ncount = 0\\nfor val in [hourHand, minHand, secondHand]:\\n    if val >= t1 and val <= t2:\\n        count += 1\\nif count == 0 or count == 3:\\n    print(\\"YES\\")\\nelse:\\n    print(\\"NO\\")\\n", "3\\n\\ndef dstr(a, b):\\n    return (b - a) % (12 * 60 * 60)\\n\\nh, m, s, t1, t2 = list(map(int, input().split()))\\n\\ncd = [(h * 60 * 60 + m * 60 + s) % (12 * 60 * 60), m * 12 * 60 + s, s * 12 * 60]\\nif dstr(cd[0], cd[2]) < dstr(cd[0], cd[1]):\\n    cd = cd[::-1]\\n    \\nt1 *= 60 * 60\\nt2 *= 60 * 60\\n\\n\\nans = False\\n\\nfor i in range(-1, 2):\\n    if dstr(cd[i], t1) <= dstr(cd[i], cd[i + 1]) \\\\\\n       and dstr(cd[i], t2) <= dstr(cd[i], cd[i + 1]):\\n        ans = True\\n\\nif len(set(cd)) == 1:\\n    ans = True\\n        \\nif ans:\\n    print(\\"YES\\")\\nelse:\\n    print(\\"NO\\")\\n", "def __starting_point():\\n\\th, m, s, t1, t2 = [int(x) for x in input().split()]\\n\\t\\n\\thand_angles = [s / 60 * 360,\\n\\t\\t\\t\\t   (m + s / 60) / 60 * 360,\\n\\t\\t\\t\\t   (h % 12 + m / 60 + s / 3600) / 12 * 360]\\n\\n\\t\\n\\tt1_angle = (t1 % 12) / 12 * 360\\n\\tt2_angle = (t2 % 12) / 12 * 360\\n\\n\\tif t1_angle > t2_angle:\\n\\t\\tt1_angle, t2_angle = t2_angle, t1_angle\\n\\n\\t# try going clockwise (from t1 to t2)\\n\\tcan_go_clockwise = True\\t\\n\\tcan_go_counterclockwise = True\\n\\tfor angle in hand_angles:\\n\\t\\tif angle > t1_angle and angle < t2_angle:\\n\\t\\t\\tcan_go_clockwise = False\\n\\t\\t\\n\\t\\tif not (angle >= t1_angle and angle <= t2_angle):\\n\\t\\t\\tcan_go_counterclockwise = False\\n\\n\\tprint(\\"YES\\" if can_go_clockwise or can_go_counterclockwise else \\"NO\\")\\n\\n__starting_point()", "h,m,s,a,b=list(map(int,input().split()))\\n\\nm+=s/60\\nh+=m/60\\nm/=5\\ns/=5\\n\\n\\nc=[h,m,s,a,b]\\nc=c+list([x+12 for x in c])\\nc=sorted(c)\\np=c.index(a)\\nfor x in [p-1,p+1]:\\n\\tfor y in [b,b+12]:\\n\\t\\tif c[x]==y:\\n\\t\\t\\tprint(\'YES\')\\n\\t\\t\\treturn\\n\\nprint(\'NO\')\\n", "def getListInt():\\n\\treturn [int(x) for x in input().split(\\" \\")]\\n\\ndef solution():\\n\\th,m,s,t1,t2 = getListInt()\\n\\tif t2 == min(t1,t2):\\n\\t\\tt1,t2 = t2,t1\\n\\tm = float(m)/5\\n\\ts = float(s)/5\\n\\n\\tnbrIn = 0\\n\\tif s>t1 and s<t2:\\n\\t\\tnbrIn += 1\\n\\n\\tif (m>t1 and m<t2) or (m == t1 and s!=0):\\n\\t\\tnbrIn += 1\\n\\n\\tif (h>t1 and h<t2) or (h == t1 and (m!=0 or s!=0)):\\n\\t\\tnbrIn += 1\\n\\n\\treturn nbrIn == 0 or nbrIn == 3 \\n\\n\\nprint(\'YES\' if solution() else \'NO\')", "def bet(x):\\n    return t1 <= x <= t2 or t2 <= x + 3600 * 12 <= t1 or t2 <= x <= t1\\n\\nread = lambda: map(int, input().split())\\nh, m, s, t1, t2 = read()\\nh %= 12\\nt1 %= 12\\nt2 %= 12\\nN = 12 * 3600 + 10\\nnt = [0] * N\\nk1 = h * 3600 + 1\\nk2 = m * 720 + 1\\nk3 = s * 720\\nt1 *= 3600\\nt2 *= 3600\\nif t1 > t2: t1, t2 = t2, t1\\nans = \'NO\'\\nflag = 1\\nif bet(k1) or bet(k2) or bet(k3):\\n    flag = 0\\nif flag:\\n    ans = \'YES\'\\nflag = 1\\nt1 += 12 * 3600\\nif bet(k1) or bet(k2) or bet(k3):\\n    flag = 0\\nif flag:\\n    ans = \'YES\'\\nprint(ans)", "h, m, s, t1, t2 = map(int, input().split())\\n\\nsplits = [False] * 12\\n\\nm = m // 5\\ns = s // 5\\nsplits[h%12] = True\\nsplits[m%12] = True\\nsplits[s%12] = True\\n\\nstart = t1 % 12\\nend = t2 % 12\\n\\nif start > end:\\n\\ta = splits[start:] + splits[:end]\\n\\tb = splits[end:start]\\nelse:\\n\\ta = splits[:start] + splits[end:]\\n\\tb = splits[start:end]\\n\\nif True in a and True in b:\\n\\tprint(\\"NO\\")\\nelse:\\n\\tprint(\\"YES\\")", "def check1(h):\\n\\tnonlocal t1,t2\\n\\tif(h==t1 or h==t2):\\n\\t\\treturn -1\\n\\tif(h>min(t1,t2) and h<max(t1,t2)):\\n\\t\\treturn 1\\n\\telse:\\n\\t\\treturn 0\\n\\ndef check2(m):\\n\\tif(m==5*t1 or m==5*t2):\\n\\t\\treturn -1\\n\\tif(m>5*min(t1,t2) and m<5*max(t1,t2)):\\n\\t\\treturn 1\\n\\telse:\\n\\t\\treturn 0\\n\\nh,m,s,t1,t2 = list(map(int,input().split()))\\nif(m!=0 or s!=0):\\n\\th+=0.5\\nif(s!=0):\\n\\tm+=0.5\\nif(h>12):\\n\\th-=12\\n\\n\\nl=[check1(h),check2(m),check2(s)]\\nfor i in range(len(l)-1,-1,-1):\\n\\tif(l[i] == -1):\\n\\t\\tl.pop(i)\\nflag=0\\nfor val in l:\\n\\tif(val!=l[0]):\\n\\t\\tflag=1\\n\\t\\tbreak\\nif(flag):\\n\\tprint(\\"NO\\")\\nelse:\\n\\tprint(\\"YES\\")\\n", "a=[0]*3\\na[0],a[1],a[2],t1,t2=map(int,input().split())\\na[0]+=a[1]/60+a[2]/3600\\na[1]=a[1]/5+a[2]/300\\na[2]/=5\\na[0]%=12\\nt1%=12\\nt2%=12\\na=sorted(a)\\nif t1>t2: t1,t2=t2,t1\\nif a[0]<t1 and t2<a[1]:\\n\\tprint(\\"YES\\")\\nelif a[1]<t1 and t2<a[2]:\\n\\tprint(\\"YES\\")\\nelse:\\n\\tif t1>a[2] and t2>a[2]:\\n\\t\\tprint(\\"YES\\")\\n\\telif t2>a[2] and t1<a[0]:\\n\\t\\tprint(\\"YES\\")\\n\\telif t1<a[0] and t2<a[0]:\\n\\t\\tprint(\\"YES\\")\\n\\telse:\\n\\t\\tprint(\\"NO\\")", "import sys\\nread = sys.stdin.readline\\n\\ndef solve(h, m, s, t1, t2):\\n    h = (h % 12 + m/60 + s/3600) * 5\\n    m = m + s/60\\n    t1 = (t1 % 12) * 5\\n    t2 = (t2 % 12) * 5\\n\\n    a = min(t1, t2)\\n    b = max(t1, t2)\\n    h_inner = a < h and h < b\\n    m_inner = a < m and m < b\\n    s_inner = a < s and s < b\\n    if h_inner and m_inner and s_inner:\\n        return \\"YES\\"\\n    if not h_inner and not m_inner and not s_inner:\\n        return \\"YES\\"\\n    return \\"NO\\"\\n\\ndef run():\\n    h, m, s, t1, t2 = list(map(int, read().replace(\\"\\\\n\\", \\"\\").split()))\\n    print(solve(h, m, s, t1, t2))\\n\\nrun()", "h,m,s,t1,t2 = list(map(int, input().split()))\\nm += s/60\\nh += m/60\\nh %= 12\\nt1, t2 = min(t1,t2), max(t1, t2)\\nif ((t1 <= h <= t2) and (t1 <= m/5 <= t2) and (t1 <= s/5 <= t2)) or \\\\\\n    (not (t1 <= h <= t2) and not (t1 <= m/5 <= t2) and not (t1 <= s/5 <= t2)):\\n    print(\'YES\')\\nelse:\\n    print(\'NO\')\\n", "h,m,s,t1,t2=list(map(int,input().split()))\\nm+=s/60\\nh+=m/60\\nm/=5\\ns/=5\\nh=h%12\\nm=m%12\\ns=s%12\\nT1=min(t1,t2)\\nT2=max(t1,t2)\\nif(T1<h<T2 and T1<m<T2 and T1<s<T2):\\n    print(\\"YES\\")\\nelif(not(T1<h<T2 or T1<m<T2 or T1<s<T2)):\\n    print(\\"YES\\")\\nelse:\\n    print(\\"NO\\")\\n\\n\\n", "H, M, S, T1, T2 = list(map(int, input().split()))\\n\\nh = (H % 12) * 30 + (M % 60) * 0.5 + (S%60) * (1/120)\\nm = (M % 60) * 6 + (S % 60) * 0.1\\ns = (S % 60) * 6 \\nt1 = (T1 % 12) * 30\\nt2 = (T2 % 12) * 30\\n\\nh,m,s = sorted([h,m,s])\\nflag = False\\n\\nif h < t1 < m and h < t2 < m:\\n    flag = True\\nelif m < t1 < s and m < t2 < s:\\n    flag = True\\nelif (s < t1 <= 360 or 0 <= t1 < h) and (s < t2 <= 360 or 0 <= t2 < h):\\n    flag = True\\n\\nif flag:\\n    print(\'YES\')\\nelse:\\n    print(\'NO\')\\n    \\n", "def main():\\n\\n    hands = [int(i) for i in input().split()]\\n    hands[0] *= 5\\n    hands[3] *= 5\\n    hands[4] *= 5\\n    for i in range(5):\\n        if hands[i] >= 60:\\n            hands[i] -= 60\\n    hands[1] += hands[2] / 60\\n    hands[0] += hands[1] / 60\\n\\n    t1, t2 = hands[3:]\\n    hands = hands[:3]\\n    # print(hands, t1, t2)\\n    if t1 > t2:\\n        (t1, t2) = (t2, t1)\\n    ans1 = True\\n    ans2 = True\\n    for t in hands:\\n        if t > t1 and t < t2:\\n            ans1 = False\\n        if (t > t2 and t < 60) or (t >= 0 and t < t1):\\n            ans2 = False\\n    # print(ans1, ans2)\\n    if ans1 or ans2:\\n        print(\\"YES\\")\\n    else:\\n        print(\\"NO\\")\\n\\ndef __starting_point():\\n    main()\\n__starting_point()", "def inside(a, b, c):\\n    return a > b and a < c\\ndef outside(a, b, c):\\n    return a < b or a > c\\nh, m, s, t1, t2 = list(map(int, input().split()))\\na = h + m/60 + s/3600\\nb = (m + s/60)/5\\nc = s/5\\nd = min(t1, t2); e = max(t1, t2)\\nf1 = inside(a,d,e) and inside(b,d,e) and inside(c,d,e)\\nf2 = outside(a,d,e) and outside(b,d,e) and outside(c,d,e)\\nif f1 or f2:\\n    print(\'YES\')\\nelse:\\n    print(\'NO\')\\n", "h,m,s,t1,t2 = list(map(int, input().split()))\\n\\nif(h==12): h=0\\nh = h*60*60 + m*60 + s\\nm = m*12*60 + s\\n\\ns = s*12*60\\n\\nif(t1==12): t1=0\\nif(t2==12): t2=0\\n\\nt1 = t1*60*60\\nt2 = t2*60*60\\n\\n#print(h,m,s,t1,t2)\\n\\ni = t2\\nonce = True\\nwhile(True):\\n\\tif i==h or i==m or i==s:\\n\\t\\tbreak\\n\\ti+=1\\n\\tif i==12*60*60:\\n\\t\\tif once:\\n\\t\\t\\ti = 0\\n\\t\\t\\tonce = False\\n\\t\\telse:\\n\\t\\t\\tbreak\\n\\tif i==t1:\\n\\t\\tprint(\\"YES\\")\\n\\t\\treturn\\ni = t1\\nonce = True\\nwhile(True):\\n\\tif i==h or i==m or i==s:\\n\\t\\tbreak\\n\\ti+=1\\n\\tif i==12*60*60:\\n\\t\\tif once:\\n\\t\\t\\ti = 0\\n\\t\\t\\tonce = False\\n\\t\\telse:\\n\\t\\t\\tbreak\\n\\tif i==t2:\\n\\t\\tprint(\\"YES\\")\\n\\t\\treturn\\n\\nprint(\\"NO\\")\\n", "from math import *\\ndef secs(h,m,s):\\n    return h*60*60+m*60+s\\n    \\ndef chop():\\n    return (int(i) for i in input().split())\\nh,m,s,t1,t2=chop()\\nsh=(h*60*60+m*60+s)% 43200;\\nsm=(m*60+s)*12% 43200\\nss=s*720% 43200\\nst1=(t1*60*60)% 43200\\nst2=(t2*60*60)% 43200\\npr1=[]\\nst1,st2=min(st1,st2),max(st1,st2)\\nfor i in range(st1,st2+1):\\n    pr1.append(i)\\npr2=[]\\nst1,st2=max(st1,st2),min(st1,st2)\\nfor i in range(st1,43201):\\n    pr2.append(i)\\nfor i in range(0,st2+1):\\n    pr2.append(i)\\nf1,f2=False,False\\nif (sm in pr1) or (ss in pr1) or (sh in pr1):\\n    f1=True\\nif (sm in pr2) or (ss in pr2) or (sh in pr2):\\n    f2=True\\nif (f1) and (f2):\\n    print(\'NO\')\\nelse:\\n    print(\'YES\')\\n", "h, m, s, t1, t2 = map(int, input().split())\\nls = s * 2\\nlm = m * 2\\nif ls != 0:\\n    lm += 1\\nlh = h % 12 * 10\\nif ls != 0 or lm != 0:\\n    lh += 1\\nt1 = t1 % 12 * 10\\nt2 = t2 % 12 * 10\\nt1, t2 = min(t1, t2), max(t1, t2)\\nans = False\\nans1 = True\\nans2 = True\\nif t1 <= ls <= t2 or t1 <= lm <= t2 or t1 <= lh <= t2:\\n    ans1 = False\\n#print(ans1)\\nif 0 <= ls <= t1 or 0 <= lm <= t1 or 0 <= lh <= t1:\\n    ans2 = False\\n#print(ans2)\\nif t2 <= ls <= 118 or t2 <= lm <= 118 or t2 <= lh <= 118:\\n    ans2 = False\\n#print(ans2)\\nif ans1 or ans2:\\n    ans = True\\nif ans:\\n    print(\'YES\')\\nelse:\\n    print(\'NO\')"]',

In [ ]:
print(apps_dataset[0])

{'problem_id': 0, 'question': "An accordion is a string (yes, in the real world accordions are musical instruments, but let's forget about it for a while) which can be represented as a concatenation of: an opening bracket (ASCII code $091$), a colon (ASCII code $058$), some (possibly zero) vertical line characters (ASCII code $124$), another colon, and a closing bracket (ASCII code $093$). The length of the accordion is the number of characters in it.\n\nFor example, [::], [:||:] and [:|||:] are accordions having length $4$, $6$ and $7$. (:|:), {:||:}, [:], ]:||:[ are not accordions. \n\nYou are given a string $s$. You want to transform it into an accordion by removing some (possibly zero) characters from it. Note that you may not insert new characters or reorder existing ones. Is it possible to obtain an accordion by removing characters from $s$, and if so, what is the maximum possible length of the result?\n\n\n-----Input-----\n\nThe only line contains one string $s$ ($1 \\le |s| \\le 500000$). It consists of lowercase Latin letters and characters [, ], : and |.\n\n\n-----Output-----\n\nIf it is not possible to obtain an accordion by removing some characters from $s$, print $-1$. Otherwise print maximum possible length of the resulting accordion.\n\n\n-----Examples-----\nInput\n|[a:b:|]\n\nOutput\n4\n\nInput\n|]:[|:]\n\nOutput\n-1", 'solutions': '["s = input()\\nn = len(s)\\nind = -1\\nf = False\\nfor i in range(n):\\n    if s[i] == \'[\':\\n        f = True\\n    elif s[i] == \':\':\\n        if f:\\n            ind = i\\n            break\\nbind = -1\\nf = False\\nfor i in range(n-1,-1,-1):\\n    if s[i] == \']\':\\n        f = True\\n    elif s[i] == \':\':\\n        if f:\\n            bind = i\\n            break\\n# print(ind,bind)\\nif ind == -1 or bind == -1:\\n    print(-1)\\nelif ind >= bind:\\n    print(-1)\\nelse:\\n    ans = 4\\n    for i in range(ind+1,bind):\\n        if s[i] == \'|\':\\n            ans += 1\\n    print(ans)\\n", "def main():\\n    s = input()\\n    \\n    if s.count(\'[\') == 0 or s.count(\']\') == 0:\\n        print(-1)\\n        return\\n    \\n    t = s[s.find(\'[\'):s.rfind(\']\')+1]\\n    \\n    if t.count(\':\') < 2:\\n        print(-1)\\n        return\\n    \\n    t = t[t.find(\':\'):t.rfind(\':\')+1]\\n    print(4 + t.count(\'|\'))\\n\\nmain()", "s = input()\\nif \'[\' in s:\\n    s = s[s.find(\'[\') + 1:]\\n    if \']\' in s:\\n        s = s[:s.rfind(\']\')]\\n        if s.count(\':\') >= 2:\\n            s = s[s.find(\':\') + 1 : s.rfind(\':\')]\\n            print(s.count(\'|\') + 4)\\n\\n        else:\\n            print(-1)\\n    else:\\n        print(-1)\\nelse:\\n    print(-1)", "import sys\\ns = input()\\nst = s.find(\'[\')\\nif st==-1: print((-1)); return\\ns = s[st+1:]\\n#print(s)\\nst = s.find(\':\')\\nif st==-1: print((-1)); return\\ns = s[st+1:]\\n#print(s)\\ns = s[::-1]\\nst = s.find(\']\')\\nif st==-1: print((-1)); return\\ns = s[st+1:]\\n#print(s)\\nst = s.find(\':\')\\nif st==-1: print((-1)); return\\ns = s[st+1:]\\n#print(s)\\nx = s.count(\'|\')\\nprint(x+4 if x>=0 else -1)\\n", "s = input()\\n\\nsb,eb,sc,ec = -1, -1, -1, -1\\n\\nfor i in range(len(s)):\\n\\tif s[i] == \'[\' and sb == -1:\\n\\t\\tsb = i\\n\\telif s[i] == \']\':\\n\\t\\teb = i\\n\\telif s[i] == \':\' and sc == -1 and sb!=-1:\\n\\t\\tsc = i\\n\\nif eb <= sb or sc>eb:\\n\\tprint(-1)\\nelif sb ==-1 or eb==-1 or sc==-1:\\n\\tprint(-1)\\nelse:\\n\\tfor i in range(sc+1, eb):\\n\\t\\tif s[i] == \':\':\\n\\t\\t\\tec = i\\n\\tif ec == -1:\\n\\t\\tprint(-1)\\n\\telse:\\n\\t\\tcnt = 0\\n\\t\\tfor i in range(sc,ec):\\n\\t\\t\\tif (s[i] == \'|\'):\\n\\t\\t\\t\\tcnt += 1\\n\\t\\tprint(cnt+4)", "s = input()\\nt_d = 0\\ntry:\\n    left = -1\\n    was_b = False\\n    for i in range(len(s)):\\n        if s[i] == \'[\' and not was_b:\\n            was_b = True\\n            continue\\n        if s[i] == \':\' and was_b:\\n            left = i\\n            break\\n        t_d += 1\\n    if left == -1:\\n        raise ArithmeticError()\\n    right = -1\\n    was_b = False\\n    for i in range(len(s) - 1, -1, -1):\\n        if s[i] == \']\' and not was_b:\\n            was_b = True\\n            continue\\n        if s[i] == \':\' and was_b:\\n            right = i\\n            break\\n        t_d += 1\\n    if right == -1 or right <= left:\\n        raise ArithmeticError()\\n    for i in range(left + 1, right):\\n        if s[i] != \'|\':\\n            t_d += 1\\n    print(len(s) - t_d)\\nexcept:\\n    print(-1)\\n        \\n", "s = input()\\n\\nmode = 0\\nl = len(s)\\nr = -1\\nfor i in range(len(s)):\\n    if mode == 0:\\n        if s[i] == \\"[\\":\\n            mode = 1\\n    if mode == 1:\\n        if s[i] == \\":\\":\\n            l = i\\n            break\\n\\nmode = 0\\nfor i in range(len(s)-1, -1, -1):\\n    if mode == 0:\\n        if s[i] == \\"]\\":\\n            mode = 1\\n    if mode == 1:\\n        if s[i] == \\":\\":\\n            r = i\\n            break\\n    \\nif l >= r:\\n    print(-1)\\nelse:\\n    c = 0\\n    for i in range(l+1, r):\\n        if s[i] == \\"|\\":\\n            c += 1\\n    print(c+4)\\n", "s = input()\\n\\nf1 = False\\nf2 = False\\nl1 = -1\\nfor l in range(len(s)):\\n    if f1 == False and s[l] == \'[\':\\n        f1 = True\\n    elif f1 == True and s[l] == \':\':\\n        f2 = True\\n        l1 = l\\n        break\\ng1 = False\\ng2 = False\\nr1 = -1\\nfor r in range(len(s) - 1, -1, -1):\\n    if g1 == False and s[r] == \']\':\\n        g1 = True\\n    elif g1 == True and s[r] == \':\':\\n        g2 = True\\n        r1 = r\\n        break\\nif (l1 == -1 or r1 == -1) or (r1 <= l1):\\n    print(-1)\\n    \\nelse:\\n    ans = 4\\n    for i in range(l1 + 1, r1):\\n        if s[i] == \'|\': ans += 1\\n    print(ans)", "s=input()\\npos1=-1\\npos2=-1\\npos3=-1\\npos4=-1\\nfor i in range(0,len(s)):\\n    if(s[i]==\'[\'):\\n        pos1=i\\n        break\\nfor i in range(len(s)-1,pos1,-1):\\n    if(s[i]==\']\'):\\n        pos2=i\\n        break\\nfor i in range(pos1,pos2+1):\\n    if(s[i]==\':\'):\\n        pos3=i\\n        break\\nfor i in range(pos2,pos3,-1):\\n    if(s[i]==\':\'):\\n        pos4=i\\n        break\\n    \\nif(pos1==-1 or pos2==-1 or pos3==-1 or pos4==-1 or len(s)<4):\\n    print(\'-1\')\\nelse:\\n    c=0\\n    for j in range(pos3,pos4):\\n        if(s[j]==\'|\'):\\n            c=c+1\\n    print(c+4)\\n", "def ii():\\n    return int(input())\\ndef mi():\\n    return list(map(int, input().split()))\\ndef li():\\n    return list(mi())\\n\\ns = input().strip()\\nn = len(s)\\nans = -1\\nfb = s.find(\'[\')\\nif fb >= 0:\\n    fc = s.find(\':\', fb)\\n    if fc >= 0:\\n        lb = s.rfind(\']\')\\n        if lb > fc:\\n             lc = s.rfind(\':\', 0, lb)\\n             if lc > fc:\\n                ans = 4 + s[fc:lc].count(\'|\')\\nprint(ans)\\n", "s = input()\\n\\ndef sovle(s):\\n\\n    i1 = s.find(\'[\')\\n    if i1 == -1:\\n        return -1\\n    s = s[i1+1:]\\n    i2 = s.find(\':\')\\n    if i2 == -1:\\n        return -1\\n\\n    s = s[i2+1 :]\\n    i1 = s.rfind(\']\')\\n    if i1 == -1:\\n        return -1\\n    s = s[:i1]\\n    i2 = s.rfind(\':\')\\n    if i2 == -1:\\n        return -1\\n    s = s[:i2]\\n    x = s.count(\'|\')\\n    return x+4\\n\\nprint(sovle(s))", "def solve(s):\\n    if s.find(\'[\') == -1:\\n        return -1\\n    s = s[s.find(\'[\'):]\\n    #print(s)\\n    if s.find(\':\') == -1:\\n        return -1\\n    s = s[s.find(\':\') + 1:]\\n    #print(s)\\n    if s.find(\']\') == -1:\\n        return -1\\n    s = s[:s.rfind(\']\')]\\n    #print(s)\\n    if s.find(\':\') == -1:\\n        return -1\\n    s = s[:s.rfind(\':\')]\\n    #print(s)\\n    return s.count(\'|\') + 4\\n\\ns = input()\\nprint(solve(s))", "s=input()\\ni=s.find(\'[\')\\nif i==-1:\\n    print(-1)\\n    return\\ns=s[i:]\\ni=s.rfind(\']\')\\n\\nif i==-1:\\n    print(-1)\\n    return\\ns=s[:i+1]\\nl,h=0,0\\nfor i,d in enumerate(s):\\n    if d==\':\':\\n        l=i\\n        break\\nfor i,d in enumerate(s):\\n    if d==\':\':\\n        h=i\\nif l==h:\\n    print(-1)\\n    return\\nc=0\\nfor i in range(l+1,h):\\n    if s[i]==\'|\':\\n        c+=1\\nprint(c+4)\\n", "from sys import stdin\\ns=stdin.readline().strip()\\nx=-1\\nfor i in range(len(s)):\\n    if s[i]==\\"[\\":\\n        x=i\\n        break\\ny=-1\\nfor i in range(len(s)-1,-1,-1):\\n    if s[i]==\\"]\\":\\n        y=i\\n        break\\nif x==-1 or y==-1 or y<x:\\n    print(-1)\\n    return\\nx1=-1\\nfor i in range(x,y):\\n    if s[i]==\\":\\":\\n        x1=i\\n        break\\ny1=-1\\nfor i in range(y-1,x,-1):\\n    if s[i]==\\":\\":\\n        y1=i\\n        break\\nif x1==-1 or y1==-1 or y1<=x1:\\n    print(-1)\\n    return\\nans=4\\nfor i in range(x1,y1):\\n    if s[i]==\\"|\\":\\n        ans+=1\\nprint(ans)\\n", "s = str(input().strip())\\ni = 0\\nn = len(s)\\nwhile i < n and s[i] != \'[\':\\n    i+=1\\nif(i == n):\\n    print(-1)\\n    return\\nj = n-1\\nwhile j > i and s[j] != \']\':\\n    j-=1\\nif(j <= i):\\n    print(-1)\\n    return\\nwhile i < j and s[i] != \':\':\\n    i+=1\\nif(i == j):\\n    print(-1)\\n    return\\nwhile j > i and s[j] != \':\':\\n    j-=1\\nif(j == i):\\n    print(-1)\\n    return\\nk = i+1\\nc = 0\\nwhile k < j:\\n    if(s[k] == \'|\'):\\n        c+=1\\n    k+=1\\nprint(c+4)\\n", "import sys\\ns = input()\\nl = len(s)\\ns_list = [x for x in s]\\n\\ncounter = 0\\ntry:\\n\\ta = s_list.index(\'[\')\\n\\tcounter += a\\n\\ts_list = s_list[a + 1:]\\nexcept:\\n\\tprint(-1)\\n\\treturn\\n\\ntry:\\n\\ta = s_list.index(\':\')\\n\\tcounter += a\\n\\ts_list = s_list[a + 1:]\\nexcept:\\n\\tprint(-1)\\n\\treturn\\n\\ns_list_rev = s_list.copy()\\ns_list_rev.reverse()\\n\\ntry:\\n\\tb = s_list_rev.index(\']\')\\n\\tcounter += b\\n\\ts_list_rev = s_list_rev[b+1:]\\nexcept:\\n\\tprint(-1)\\n\\treturn\\n\\ntry:\\n\\tb = s_list_rev.index(\':\')\\n\\tcounter += b\\n\\ts_list_rev = s_list_rev[b+1:]\\nexcept:\\n\\tprint(-1)\\n\\treturn\\ns_list_rev = [x for x in s_list_rev if x != \'|\']\\ncounter += len(s_list_rev)\\nprint(l - counter)", "MOD = 10**9 + 7\\nI = lambda:list(map(int,input().split()))\\n\\ns = input()\\nres = 0\\nn = len(s)\\nst = -1\\ne = -1\\nfor i in range(n):\\n    if s[i] == \'[\':\\n        st = i\\n        break\\nfor i in range(n-1, -1, -1):\\n    if s[i] == \']\':\\n        e = i\\n        break\\n# print(st , e)\\nif st > e or st == -1 or e == -1:\\n    print(-1)\\n    return\\na = -1\\nb = -1\\nfor i in range(st, e):\\n    if s[i] == \':\':\\n        a = i\\n        break\\nfor i in range(e, st, -1):\\n    if s[i] == \':\':\\n        b = i\\n        break\\nif a == b or a == -1 or b == -1:\\n    print(-1)\\n    return\\ncount = 0\\nfor i in range(a, b):\\n    if s[i] == \'|\':\\n        count += 1\\nprint(4 + count)", "s=input()\\nst=\\"\\"\\nidx=-1\\nfor i in range(len(s)):\\n    if s[i]==\'[\':\\n        idx=i\\n        break\\nif idx==-1:\\n    print(-1)\\n    return\\nidxl=-1\\nfor i in range(len(s)-1,-1,-1):\\n    if s[i]==\']\' and i>idx:\\n        idxl=i\\n        break\\nif idxl==-1:\\n    print(-1)\\n    return\\ncol=col2=-1\\nfor i in range(len(s)):\\n    if s[i]==\':\' and i>idx and i<idxl:\\n        col=i\\n        break\\nif col==-1:\\n    print(-1)\\n    return\\nfor i in range(len(s)-1,-1,-1):\\n    if s[i]==\':\' and i>col and i<idxl:\\n        col2=i\\n        break\\nif col2==-1:\\n    print(-1)\\n    return\\nans=0\\nfor i in range(col+1,col2):\\n    if s[i]==\'|\':\\n        ans+=1\\nprint(4+ans)\\n    \\n\\n\\n", "s = input()\\nrev = s[::-1]\\n\\nleft = s.find(\\"[\\")\\nif left != -1:\\n    left = s.find(\\":\\", left)\\n\\nright = rev.find(\\"]\\")\\nif right != -1:\\n    right = rev.find(\\":\\", right)\\n\\nif left == -1 or right == -1:\\n    print(-1)\\n    return\\nright = len(s)-right-1\\nif left >= right:\\n    print(-1)\\n    return\\n\\nprint(4 + s[left:right].count(\\"|\\"))\\n", "def ba(s):\\n    c1 = s.find(\'[\')\\n    c2 = s.find(\':\', c1+1)\\n    c3 = s.rfind(\']\', c2+1)\\n    c4 = s.rfind(\':\', c2+1, c3)\\n    if -1 in [c1, c2, c3, c4]:\\n        return -1\\n    return s.count(\'|\', c2, c4)+4\\n\\n\\nprint(ba(input()))\\n\\n", "s = input()\\nif \'[\' in s and \']\' in s:\\n    a = s.index(\'[\') + 1\\n    b = len(s)-s[::-1].index(\']\') - 1\\nelse:\\n    print(-1)\\n    return\\ns = s[a:b]\\nif s.count(\':\') >= 2:\\n    a = s.index(\':\')+1\\n    b = len(s)-s[::-1].index(\':\')-1\\nelse:\\n    print(-1)\\n    return\\nc = 0\\nfor el in s[a:b]:\\n    if el ==\'|\':\\n        c += 1\\nprint(4 + c)", "s = input()\\n\\nb = [0]*len(s)\\n\\nob = 0\\ncc = 0\\np = -1\\nq = -1\\n\\ncount = 0\\n\\nfor ind,c in enumerate(s):\\n    if c == \'[\':\\n        ob = 1\\n    elif c == \':\' and p >= 0:\\n        q = ind\\n    elif c == \':\' and ob == 1 and p < 0:\\n        p = ind\\n    elif c == \']\' and q >= 0:\\n        cc = q\\n    elif c == \'|\':\\n        count += 1\\n    b[ind] = count\\n\\nif cc > 0:\\n    print( 4 + b[cc]-b[p])\\nelse:\\n    print(-1)\\n", "s = input()\\nif \'[\' in s and \']\' in s and \':\' in s:\\n  e = s.count(\':\')\\n  if e<2:\\n    print(-1)\\n  else:\\n    a = s.index(\'[\')\\n    b = len(s)-1-s[::-1].index(\']\')\\n    if b<a:\\n      print(-1)\\n    else:\\n      if s[a+1:b].count(\':\')<2:\\n        print(-1)\\n      else:\\n        st1 = True\\n        count = 0\\n        for i in range(a+1, b):\\n          if st1 and s[i]==\':\':\\n            pos1 = i\\n            st1 = False\\n          if s[i]==\':\':\\n            pos2 = i\\n      \\n        for i in range(pos1+1, pos2):\\n          if s[i]==\'|\':\\n            count+=1\\n      \\n        print(count+4)\\nelse:\\n  print(-1) ", "s=input()\\ni1=-1\\ni2=-1\\nk1=-1\\nk2=-1\\nc=0\\nfor i in range(len(s)):\\n  if(s[i]==\'[\'):\\n    i1=i\\n    break\\nfor i in range(len(s)-1,-1,-1):\\n  if(s[i]==\']\'):\\n    i2=i\\n    break\\nfor i in range(i1,i2+1):\\n  if(s[i]==\':\'):\\n    k1=i\\n    break\\nfor i in range(i2,i1-1,-1):\\n  if(s[i]==\':\'):\\n    k2=i\\n    break\\nfor i in range(k1,k2+1):\\n  if(s[i]==\'|\'):\\n    c+=1\\n\\nif(i1==-1 or i2==-1 or i1>=i2 or k1==-1 or k2==-1 or k1==k2):\\n  print(-1)\\nelse:\\n  print(4+c)", "s = input()\\nl = 0\\nend = 0\\ni = 1\\n\\nwhile i <= len(s):\\n    if l == 0 and s[-i] == \']\':\\n        l += 1\\n    elif l == 1 and s[-i] == \':\':\\n        l += 1\\n        end = len(s) - i\\n        break\\n    i += 1\\n\\nif l < 2:\\n    print(-1)\\n    return\\n\\nfor i in range(0, end):\\n    if l >= 4 and s[i] == \'|\':\\n        l += 1\\n    elif l == 2 and s[i] == \'[\':\\n        l += 1\\n    elif l == 3 and s[i] == \':\':\\n        l += 1\\n\\nif l >= 4:\\n    print(l)\\nelse:\\n    print(-1)"]', 'test_cases': '[{"input": "|[a:b:|]\\n", "output": "4\\n"}, {"input": "|]:[|:]\\n", "output": "-1\\n"}, {"input": ":][:\\n", "output": "-1\\n"}, {"input": ":[]:\\n", "output": "-1\\n"}, {"input": "[[:]]\\n", "output": "-1\\n"}, {"input": "[::]\\n", "output": "4\\n"}, {"input": "]:|:[\\n", "output": "-1\\n"}, {"input": ":::::]\\n", "output": "-1\\n"}, {"input": "::::]\\n", "output": "-1\\n"}, {"input": "::[]\\n", "output": "-1\\n"}, {"input": "[]\\n", "output": "-1\\n"}, {"input": "[a|[::]\\n", "output": "4\\n"}, {"input": "dsfdsfds\\n", "output": "-1\\n"}, {"input": ":[||]:\\n", "output": "-1\\n"}, {"input": "::]\\n", "output": "-1\\n"}, {"input": ":::]\\n", "output": "-1\\n"}, {"input": "[||]\\n", "output": "-1\\n"}, {"input": ":[[[:]]]:\\n", "output": "-1\\n"}, {"input": "::]::[:]::[::\\n", "output": "-1\\n"}, {"input": "[:|:]\\n", "output": "5\\n"}, {"input": "[::]aaaaaaaa\\n", "output": "4\\n"}, {"input": "[[::]|]\\n", "output": "4\\n"}, {"input": "[::::\\n", "output": "-1\\n"}, {"input": "][\\n", "output": "-1\\n"}, {"input": "[||]][[]\\n", "output": "-1\\n"}, {"input": "][k:\\n", "output": "-1\\n"}, {"input": "::|[]\\n", "output": "-1\\n"}, {"input": "[:\\n", "output": "-1\\n"}, {"input": "||||\\n", "output": "-1\\n"}, {"input": "||]ekq\\n", "output": "-1\\n"}, {"input": "]:|||:]\\n", "output": "-1\\n"}, {"input": "|||[|||:[m[[n[[[xuy|:[[[:|:[:k[qlihm:ty[\\n", "output": "-1\\n"}, {"input": "aaaaa[[[[[:[[[[a]]\\n", "output": "-1\\n"}, {"input": "[hellocodeforces::]\\n", "output": "4\\n"}, {"input": "[::]lolxd\\n", "output": "4\\n"}, {"input": "sasixyu:[[:||ld[:[dxoe\\n", "output": "-1\\n"}, {"input": "[:|||:\\n", "output": "-1\\n"}, {"input": "topkek[::]\\n", "output": "4\\n"}, {"input": "[[||]]\\n", "output": "-1\\n"}, {"input": "[\\n", "output": "-1\\n"}, {"input": "|[::||::]]a\\n", "output": "6\\n"}, {"input": ":]\\n", "output": "-1\\n"}, {"input": "]::]\\n", "output": "-1\\n"}, {"input": "r|x\\n", "output": "-1\\n"}, {"input": "|\\n", "output": "-1\\n"}, {"input": ":][:|||\\n", "output": "-1\\n"}, {"input": "]]::[[]]::\\n", "output": "-1\\n"}, {"input": "]f:|efw][jz[|[[z][[g]i|[\\n", "output": "-1\\n"}, {"input": "]::[\\n", "output": "-1\\n"}, {"input": "|:[[][:cv|\\n", "output": "-1\\n"}, {"input": ":y]j]tz:e[p[\\n", "output": "-1\\n"}, {"input": "::::\\n", "output": "-1\\n"}, {"input": "||\\n", "output": "-1\\n"}, {"input": "]|[hhf[\\n", "output": "-1\\n"}, {"input": "abide\\n", "output": "-1\\n"}, {"input": "|c[]][zx]|[[[[j[::nx[|[:ou[u]\\n", "output": "5\\n"}, {"input": "|:]\\n", "output": "-1\\n"}, {"input": "]:|:][:||:]\\n", "output": "6\\n"}, {"input": "]:]\\n", "output": "-1\\n"}, {"input": "d[\\n", "output": "-1\\n"}, {"input": ":|:]\\n", "output": "-1\\n"}, {"input": "k::]k|iv|]|g[|r[q:|[:[r[cj]||mjm|[|[|[|:[\\n", "output": "5\\n"}, {"input": ":|f[|e]e:|\\n", "output": "-1\\n"}, {"input": "][:|:\\n", "output": "-1\\n"}, {"input": "|rh]|[|:[v|||||i\\n", "output": "-1\\n"}, {"input": "y:[|[]b[][ug|e[\\n", "output": "-1\\n"}, {"input": "[:::]\\n", "output": "4\\n"}, {"input": "[:]:[:]\\n", "output": "4\\n"}, {"input": "::]]:::\\n", "output": "-1\\n"}, {"input": "[:||:|]\\n", "output": "6\\n"}, {"input": "d]k[[::[||[:tpoc[||[:\\n", "output": "-1\\n"}, {"input": ":]||haha||[:\\n", "output": "-1\\n"}, {"input": ":]||ahaha||[:\\n", "output": "-1\\n"}, {"input": "[][]\\n", "output": "-1\\n"}, {"input": ":|]:::]]|:|||||]]]:|\\n", "output": "-1\\n"}, {"input": "||:][:||\\n", "output": "-1\\n"}, {"input": "|:][:\\n", "output": "-1\\n"}, {"input": "]\\n", "output": "-1\\n"}, {"input": "[:::\\n", "output": "-1\\n"}, {"input": "ss:]]n:w:kzxiwpdoce|d:]][:nmw|b:hs\\n", "output": "-1\\n"}, {"input": "::][::\\n", "output": "-1\\n"}, {"input": "[:tk]v|hd:h:c[s\\n", "output": "-1\\n"}, {"input": "md:o:|r:[uuzcov]wy]|[:[imwc\\n", "output": "-1\\n"}, {"input": ":::]w\\n", "output": "-1\\n"}, {"input": "wd[]jcq[[]f|:\\n", "output": "-1\\n"}, {"input": ":aj::pxblo]]]:o|x|:|]y:wn]:[:v:m\\n", "output": "-1\\n"}, {"input": "oeq]pp|i:[tan|][:ncsp::\\n", "output": "-1\\n"}, {"input": "m][js]x]a:l\\n", "output": "-1\\n"}, {"input": "[:]\\n", "output": "-1\\n"}, {"input": "[asfd:khj]\\n", "output": "-1\\n"}, {"input": ":i:]f|cau\\n", "output": "-1\\n"}, {"input": "ljjjsv:h|]o:]k\\n", "output": "-1\\n"}, {"input": "aaaa\\n", "output": "-1\\n"}, {"input": "qj|]gd:i:::[|ur[e[e:]ay::k:\\n", "output": "-1\\n"}, {"input": "qod:|nw]sfr:g|::[]ajs:\\n", "output": "-1\\n"}, {"input": "]zpgjpy:]:sz|[miz\\n", "output": "-1\\n"}, {"input": "]ty:|:cjk::c:[[]tm\\n", "output": "-1\\n"}, {"input": "umfqrr::m]w]g::a|]|::]duhhxmzqs:gbo]br|xz|[g][ou:v[e[u|:y[||k:|[zqd:p:wf:a:gb\\n", "output": "-1\\n"}, {"input": ":j:]xp:pnyh\\n", "output": "-1\\n"}, {"input": ":]|[:\\n", "output": "-1\\n"}, {"input": "]h:y[u:bg\\n", "output": "-1\\n"}, {"input": ":am:trjm|]e[[[vm[:|pv\\n", "output": "-1\\n"}, {"input": ":[||||||]:\\n", "output": "-1\\n"}, {"input": ":|[:qw[|:yr]c:p][]|n:qql[ulp:ph:|||adcg\\n", "output": "5\\n"}, {"input": ":a::[vd|vwq|r:][]:|::\\n", "output": "-1\\n"}, {"input": "|v]efoi::b|ov]:]|||:vk[q]is|[]|ku|]||wk[[|[q::]g|\\n", "output": "4\\n"}, {"input": "[w:||j:iiasd]gz||o:yw[::b::[[[m[oe[|oh]jh]:yjwa\\n", "output": "8\\n"}, {"input": "||::k[is|m|]|::i\\n", "output": "-1\\n"}, {"input": "t]g]ney::]hca]:|]|\\n", "output": "-1\\n"}, {"input": "]g[:]|u[d]\

In [ ]:
client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

In [ ]:
# ===========================================
# PART 2: Introduce Harder Problems from APPS
# ===========================================

!pip install -q datasets google-generativeai openai pandas tqdm

import os
import re
import pandas as pd
from datasets import load_dataset
from tqdm import tqdm
import google.generativeai as genai
from openai import OpenAI

# ------------------------
# Environment setup
# ------------------------
os.environ["OPENAI_API_KEY"] = ""
os.environ["GOOGLE_API_KEY"] = ""

genai.configure(api_key=os.environ["GOOGLE_API_KEY"])
client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
GEMINI_MODEL = "gemini-2.5-flash"

# ------------------------
# Utility Functions
# ------------------------
def extract_code(text):
    if not text:
        return ""
    code = re.sub(r"```(?:python)?\n", "", text)
    code = re.sub(r"```", "", code)
    return code.strip()

def generate_code_gpt(prompt, temperature=0.7):
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature,
    )
    return extract_code(response.choices[0].message.content)

def generate_code_gemini(prompt, temperature=0.7):
    model = genai.GenerativeModel(GEMINI_MODEL)
    try:
        response = model.generate_content(
            prompt,
            generation_config={"temperature": temperature},
        )
        if hasattr(response, "text") and response.text:
            return extract_code(response.text)
        elif hasattr(response, "candidates") and response.candidates:
            return extract_code(response.candidates[0].content.parts[0].text)
        else:
            return ""
    except Exception as e:
        return f"# Gemini Error: {e}"

def check_pass(problem, code):
    try:
        local_vars = {}
        exec(code, {}, local_vars)
        exec(problem["test"], {}, local_vars)
        return 1, ""
    except Exception as e:
        return 0, str(e)

# ------------------------
# Prompt Templates
# ------------------------
def chain_of_thought_refined(problem_text):
    return f"""
You are a Python expert.
Write a function that strictly follows the given signature.
Include all edge cases (empty lists, invalid inputs, performance limits).
Do not add any explanation — only provide the function code.

Problem:
{problem_text}
"""

def stepwise_chain_of_thought_refined(problem_text):
    return f"""
You are a Python expert.
Solve the problem step by step.
1. Plan your approach.
2. Implement the function following the signature.
3. Handle edge cases and constraints.
Do not add explanations outside the code.

Problem:
{problem_text}
"""

# # ------------------------
# # Load APPS Dataset (New Source)
# # ------------------------
# # "dz1/CodeScore-APPS" is a modern, script-free APPS dataset mirror
# apps_dataset = load_dataset("dz1/CodeScore-APPS", split="test")

# Filter only harder problems (competition-level)
apps_hard = [p for p in apps_dataset if p.get("difficulty", "") == "competition"]
selected_apps = apps_hard[:3]  # select 5 challenging problems

# print(f"Loaded {len(selected_apps)} hard APPS problems for Part 2.\n")

# ------------------------
# Evaluation Loop
# ------------------------
strategies = [
    ("CoT", chain_of_thought_refined),
    ("SCoT", stepwise_chain_of_thought_refined)
]

records = []

for idx, prob in enumerate(tqdm(selected_apps, desc="Evaluating APPS Hard Problems")):
    prob_text = prob.get("question", "")
    test_code = prob.get("input_output", "")

    problem = {"prompt": prob_text, "test": test_code}

    for strat_name, strat_fn in strategies:
        prompt = strat_fn(problem["prompt"])

        # GPT
        gpt_code = generate_code_gpt(prompt)
        gpt_pass, gpt_err = check_pass(problem, gpt_code)
        records.append([idx, "GPT-4o-mini", strat_name, gpt_pass, prompt, gpt_code, gpt_err])

        # Gemini
        gem_code = generate_code_gemini(prompt)
        gem_pass, gem_err = check_pass(problem, gem_code)
        records.append([idx, GEMINI_MODEL, strat_name, gem_pass, prompt, gem_code, gem_err])

# ------------------------
# Save Results
# ------------------------
df = pd.DataFrame(records, columns=[
    "ProblemID", "Model", "PromptType", "Pass@1", "Prompt", "GeneratedCode", "Error"
])
df.to_csv("apps_failures_part2.csv", index=False)
print("\n✅ Results saved to apps_failures_part2.csv")
df.head()
df

Evaluating APPS Hard Problems:   0%|          | 0/3 [00:00<?, ?it/s]

4
1313

Evaluating APPS Hard Problems:   0%|          | 0/3 [25:36<?, ?it/s]

KeyboardInterrupt: Interrupted by user

In [ ]:
prompt = "Write a Python function to check if a number is prime."
print("🔹 Testing Gemini...")
try:
    from google.generativeai import GenerativeModel
    model = GenerativeModel("gemini-1.5-flash")
    response = model.generate_content(prompt)
    print("✅ Gemini response:", response.text[:200])
except Exception as e:
    print("❌ Gemini error:", e)

🔹 Testing Gemini...

WARNING:tornado.access:404 POST /v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 495.35ms

❌ Gemini error: 404 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: models/gemini-1.5-flash is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.

In [ ]:
import google.generativeai as genai

genai.configure(api_key="")

for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)

models/gemini-2.5-pro-preview-03-25
models/gemini-2.5-flash-preview-05-20
models/gemini-2.5-flash
models/gemini-2.5-flash-lite-preview-06-17
models/gemini-2.5-pro-preview-05-06
models/gemini-2.5-pro-preview-06-05
models/gemini-2.5-pro
models/gemini-2.0-flash-exp
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-exp-image-generation
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.0-flash-preview-image-generation
models/gemini-2.0-flash-lite-preview-02-05
models/gemini-2.0-flash-lite-preview
models/gemini-2.0-pro-exp
models/gemini-2.0-pro-exp-02-05
models/gemini-exp-1206
models/gemini-2.0-flash-thinking-exp-01-21
models/gemini-2.0-flash-thinking-exp
models/gemini-2.0-flash-thinking-exp-1219
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/learnlm-2.0-flash-experimental
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image-preview
models/gemini-2.5-flash-image
models/gemini-2.5-flash-preview-09-2025
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025

In [ ]:
import os
os.environ["OPENAI_API_KEY"] = ""

print("✅ Updated key:", os.environ["OPENAI_API_KEY"][:10], "...")  # just to verify it's set

✅ Updated key: sk-proj-3A ...

In [ ]:
from openai import OpenAI
client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

try:
    models = client.models.list()
    print("✅ OpenAI connection successful! Total models:", len(models.data))
except Exception as e:
    print("❌ Connection failed:", e)

✅ OpenAI connection successful! Total models: 76